### ISSUE TITLE
似乎容易出现 EAI_AGAIN 这个错误，似乎是DNS解析问题

### ISSUE THREAD

**Issue by BlueSkyXN** [LLM-Red-Team/deepseek-free-api#14]
```
Stream response error: Error: getaddrinfo EAI_AGAIN chat.deepseek.com
deepseek-free-api  |     at AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)
deepseek-free-api  |     at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:610:25)
deepseek-free-api  |     at RedirectableRequest.emit (node:events:531:35)
deepseek-free-api  |     at eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:38:24)
deepseek-free-api  |     at ClientRequest.emit (node:events:519:28)
deepseek-free-api  |     at TLSSocket.socketErrorListener (node:_http_client:500:9)
deepseek-free-api  |     at TLSSocket.emit (node:events:519:28)
deepseek-free-api  |     at emitErrorNT (node:internal/streams/destroy:169:8)
deepseek-free-api  |     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
deepseek-free-api  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
deepseek-free-api  |     at Axios.request (file:///app/node_modules/axios/lib/core/Axios.js:45:41)
deepseek-free-api  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
deepseek-free-api  |     at async file:///app/dist/index.js:1127:21
deepseek-free-api  |     at async requestToken (file:///app/dist/index.js:1126:18)
deepseek-free-api  |     at async acquireToken (file:///app/dist/index.js:1168:14)
deepseek-free-api  |     at async clearContext (file:///app/dist/index.js:1178:17)
deepseek-free-api  |     at async file:///app/dist/index.js:1200:7
```

用的docker compose部署，尝试更新hosts/dns没有有效作用

**Comment by BlueSkyXN** [comment]
我改用原生nodejs运行后恢复正常
目前不能确定是否和我的docker禁用了iptable控制有关系

**Comment by riverai** [comment]
我也是这个错误，也是用的docker compose
