### ISSUE TITLE
非中国 IP 可能无法使用

### ISSUE THREAD

**Issue by Vinlic** [LLM-Red-Team/deepseek-free-api#32]
目前 DeepSeek 官网对于非中国 IP 可能采取屏蔽措施，请部署在中国境内服务器或使用代理。

**Comment by Fan-Bob** [comment]
挂代理能访问官网 但还是报第三方错误，用deepseek-think

**Comment by luoluoluo22** [comment]
我来说明一下细节，render、vercel部署上去均不能使用，原因是非中国ip。服务器会报错误日志，以下是日志

[2025-02-03 11:39:47.890][info][index<1346,20>] [ { role: 'user', content: '你好' } ]
[2025-02-03 11:39:47.930][error][index<1403,22>] Stream response error: Error: 创建会话失败，可能是账号或IP地址被封禁
    at createSession (file:///var/task/dist/index.js:1311:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async file:///var/task/dist/index.js:1351:39
    at async /completions (file:///var/task/dist/index.js:2261:16)

本地docker和原生部署或者用中国服务器可用。

再补充一下，roocline基本接入不可用，因为token太长，导致服务器繁忙。之前是好的。害！所以短的比如聊天可以接入，目前方案是硅基流动的api接入，新用户有14元优惠

邀请码：
HdZPhafW
邀请链接：
https://cloud.siliconflow.cn/i/HdZPhafW

希望大家少走弯路！

**Comment by uttamthegoat** [comment]
I get an error saying unable to access website. It seems to be Cloudflare error
